client:
  ssl:
    key-store-type: PKCS12
    key-store: classpath:server.p12
    key-store-password: changeit
    trust-store: "classpath:server-truststore.p12"
    trust-store-password: changeit
    enabled: true
    trust-store-type: PKCS12



