/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.algo.ref.ex;

import com.algo.ref.ex.socket.SimpleServer;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        SimpleServer classUnderTest = new SimpleServer();
        assertNotNull(classUnderTest, "app should have a greeting");
    }
}
